


```{r}
# Load Tidyverse, janitor and USAboundaries, tidycensus
install.packages("USAboundaries")
library(tidycensus)
library(tidyverse)
library(janitor)
library(USAboundaries)

```



```{r}
#USAboundaries changed the state names to two-letter abbreviations. I needed to glimpse it here to see what the variable names were.
glimpse(state_codes)
```



```{r}
#Scraped the state by state data from The Covid Tracking Project.
covid_data <- read_csv("https://covidtracking.com/api/v1/states/current.csv")
```

```{r}
#Made all column names lower case and separated by underscores.
#Selected just the total test results and state name columns.
covid_data_working <- covid_data %>%
  clean_names() %>%
  select(state, total_test_results)
  glimpse(covid_data_working)
```

```{r}
#Loaded the census data API and teh state population variable code.
census_api_key("549950d36c22ff16455fe196bbbd01d63cfbe6cf")
#acs_variables <- load_variables(2017, "acs5" )

state_population <- get_acs(geography = "state", 
              variables="B01001_001")
```

```{r}
#Cleaned the state population data. To get mutate to work, I had to take our Puerto Rico because USAboundaries wouldn't work on Puerto Rico.
#Filtered out the states whose data grade was a C or below. Some B-grade states were filtered out because total test results were not per person, but instead per specimen or did not include private lab totals. States with B grades that were filtered out were Indiana, Iowa, Maine, Massachusetts, California.
state_population_working <- state_population %>%
 clean_names() %>%
  filter(name != "Puerto Rico") %>% 
  mutate(state = state_codes$state_abbr[state_codes$state_name==name]) %>%
 filter(!(state %in% c("UT","VT","WY","IN","IA","MA","ME","CA","CO","CT","DE","FL","HI","ID","KS","MT","NE","NV","NH","NM","NC","ND","SD")))
  
``` 

```{r}
#Joined the total tests and state populations on state abbreviation.
#Created a new column with a per state calculation of percent of poulation tested.
tests_per_state_population <- covid_data_working %>%
  inner_join(state_population_working, by=c("state" = "state")) %>%
  mutate(percent_of_population_tested = (total_test_results/estimate)*100)
  
```

```{r}
#What I have done and discovered so far

#Since the coronovirus pandemic outbreak hit America, the lack of a strategic plan to contain the spread through mass testing has been at the forefront of a conversation on the nation's preparedness. Countries such as Iceland, South Korea and Thailand have managed to test wide swaths of their population in short amounts of time, and in doing so, have contained the spread and asymptomatic positive cases.

#My data analysis aims to assess the percentage of the population of 26 states and the District of Columbia 

#My dataset includes all A-grade states and those B-grade states who had no potential conflict with the collection of total number of tests. For example, the CTP gave Massachusetts a B grade because they are including in the total test count people that were tested twice.

# The Covid Tracking Project since early March has maintained a database of avalable covid-19 testing data from the 50 states, five territories and the District of Columbia from public health departments and news reports. Hundreds of volunteers from developers and journalists to researchers and designers staff the team.
```

  